version: '2'
services:
  smb:
    image: rizo928/smb
    networks:
      - backend-net
    ports:
      - 5000:5000
    environment:
      - TZ=America/New_York
    volumes:
      - ./config.ini/:/app/config.ini
    container_name: smb
    restart: always
networks:
  backend-net:
    external:
      name: backend-net
